# Generated by Django 3.1.6 on 2021-02-03 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('FAILED', 'Failed'), ('COMPLETED', 'Completed')], max_length=25, null=True)),
                ('payment_type', models.CharField(blank=True, choices=[('ACH', 'ACH'), ('CRYPTO', 'ETH'), ('CHEQUE', 'Cheque')], max_length=100, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=20, default=None, max_digits=40, null=True)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('ETH', 'ETH'), ('DAI', 'DAI'), ('BTC', 'BTC')], max_length=10, null=True)),
                ('external_unique_id', models.CharField(max_length=200, null=True)),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, choices=[('STATUS_PENDING', 'Pending'), ('STATUS_PAYMENT_PENDING', 'Payment Pending'), ('STATUS_PAYMENT_SCHEDULED', 'Payment Scheduled'), ('STATUS_FAILED', 'Failed'), ('STATUS_COMPLETED', 'Completed'), ('STATUS_CANCELLED', 'Cancelled')], max_length=25, null=True)),
                ('type', models.CharField(choices=[('TYPE_PAYROLL', 'Payroll'), ('TYPE_BONUS', 'Bonus')], default='TYPE_PAYROLL', max_length=25)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=14, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('payment', models.ManyToManyField(to='payroll.Payment')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
